version: "3.8"

services:
  dashmagify:
    image: dashmagify:prod
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashmagify.rule=Host(`painel.fluxerautoma.shop`)"
        - "traefik.http.routers.dashmagify.entrypoints=websecure"
        - "traefik.http.routers.dashmagify.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.dashmagify.loadbalancer.server.port=80"
    networks:
      - FluxerNet

networks:
  FluxerNet:
    external: true

