// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgmtbffyvygfjkwadkrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnbXRiZmZ5dnlnZmprd2Fka3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODAzMDYsImV4cCI6MjA2MTQ1NjMwNn0.v3ek8Dkl60OuvzyJEI5zCXsBBNNGfWdmL2e55Lgdgow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);